# Generated by Django 5.0.3 on 2024-03-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Category name')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=30, verbose_name='SubCategory name')),
                ('date', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(related_name='sub_category', to='main.category')),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'SubCategories',
                'ordering': ['-date', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Product name')),
                ('price', models.FloatField(verbose_name='Product price')),
                ('image', models.ImageField(upload_to='main_images', verbose_name='Product image')),
                ('category', models.ManyToManyField(related_name='category_product', to='main.category')),
                ('subcategory', models.ManyToManyField(related_name='subcategory_product', to='main.subcategory')),
            ],
        ),
    ]
